apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jcasc
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  jcasc.yaml: |
{{ tpl (.Files.Get "files/jcasc.yaml") . | indent 4 }}
