apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-jobs
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
