apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  jenkins-admin-id: {{ .Values.controller.admin.id | quote }}
  jenkins-admin-password: {{ required "controller.admin.password is required" .Values.controller.admin.password | quote }}
