FROM jenkins/inbound-agent:3355.v388858a_47b_33-20-jdk21
USER root
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    git \
    unzip \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*
USER jenkins
